<!--

    Copyright (C) 2012-2020 the original author or authors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.ninjaframework</groupId>
    <artifactId>ninja</artifactId>
    <packaging>pom</packaging>
    <version>7.0.1-SNAPSHOT</version>
    <url>https://www.ninjaframework.org</url>
    <name>${project.artifactId}</name>
    <description>Ninja is a full stack web framework for Java.
        Rock solid, fast, and super productive.</description>
        
        <developers>
            <developer>
                <name>Raphael A. Bauer</name>
                <email>ra@raphaelbauer.com</email>
                <url>http://www.raphaelbauer.com</url>
                <roles>
                    <role>Lead Architect</role>
                </roles>
            </developer>
            <developer>
                <name>Joe Lauer</name>
                <email>joe@fizzed.com</email>
                <organization>Fizzed, Inc.</organization>
                <organizationUrl>http://fizzed.com</organizationUrl>
                <roles>
                    <role>Lead Architect</role>
                </roles>
            </developer>
        </developers>

    <modules>
        <module>ninja-core</module>
        <module>ninja-postoffice</module>
        <module>ninja-jaxy-routes</module>
        <module>ninja-websockets-jsr356</module>
        <module>ninja-metrics</module>
        <module>ninja-metrics-graphite</module>
        <module>ninja-metrics-ganglia</module>
        <module>ninja-metrics-librato</module>
        <module>ninja-metrics-influxdb</module>
        <module>ninja-servlet</module>
        <module>ninja-db-classic</module>
        <module>ninja-standalone</module>
        <module>ninja-test-utilities</module>
        <module>ninja-servlet-integration-test</module>
        <module>ninja-servlet-jpa-blog-integration-test</module>
        <module>ninja-maven-plugin</module>
        <!-- archetypes -->
        <module>ninja-servlet-jpa-blog-archetype</module>
        <module>ninja-servlet-archetype-simple</module>
    </modules>

    <!-- pin encoding to utf-8 -->
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <siteProjectVersion>${project.version}</siteProjectVersion>
        <jetty.version>9.4.53.v20231009</jetty.version>
        <hibernate.version>4.3.8.Final</hibernate.version>
        <jackson.version>2.22.0</jackson.version>
        <guice.version>6.0.0</guice.version>
        <metrics.version>3.2.6</metrics.version>
        <slf4j.version>1.7.30</slf4j.version>
        <!--<powermock.version>2.0.9</powermock.version>-->
        <!-- Formatting options for Netbeans IDE -->
        <org-netbeans-modules-editor-indent.CodeStyle.usedProfile>project</org-netbeans-modules-editor-indent.CodeStyle.usedProfile>
        <org-netbeans-modules-editor-indent.CodeStyle.project.spaces-per-tab>4</org-netbeans-modules-editor-indent.CodeStyle.project.spaces-per-tab>
        <org-netbeans-modules-editor-indent.CodeStyle.project.tab-size>4</org-netbeans-modules-editor-indent.CodeStyle.project.tab-size>
        <org-netbeans-modules-editor-indent.CodeStyle.project.indent-shift-width>4</org-netbeans-modules-editor-indent.CodeStyle.project.indent-shift-width>
        <org-netbeans-modules-editor-indent.CodeStyle.project.expand-tabs>true</org-netbeans-modules-editor-indent.CodeStyle.project.expand-tabs>
        <org-netbeans-modules-editor-indent.CodeStyle.project.text-limit-width>80</org-netbeans-modules-editor-indent.CodeStyle.project.text-limit-width>
        <org-netbeans-modules-editor-indent.CodeStyle.project.text-line-wrap>none</org-netbeans-modules-editor-indent.CodeStyle.project.text-line-wrap>
        <!-- end formatting options for Netbeans -->
    </properties>

    <!-- Fix version 1.8 of java compiler in all submodules: -->
    <build>

        <pluginManagement>
        
            <plugins>
                
                <plugin>
                    <artifactId>maven-release-plugin</artifactId>
                    <version>2.5.3</version>
                    <configuration>
                        <!-- bump submodule versions automatically -->
                        <autoVersionSubmodules>true</autoVersionSubmodules>
                        <!-- install next final version in local repo, so that
                        tests on archetypes work -->
                        <preparationGoals>clean install</preparationGoals>
                        <useReleaseProfile>false</useReleaseProfile>
                        <releaseProfiles>release</releaseProfiles>
                        <goals>deploy</goals>
                    </configuration>
                </plugin>
            
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.9.0</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.1.2</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>3.2.1</version>
                </plugin>

                <!--
                        This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the
                        Maven build itself.
                -->
                <plugin>
                    <groupId>org.eclipse.m2e</groupId>
                    <artifactId>lifecycle-mapping</artifactId>
                    <version>1.0.0</version>
                    <configuration>
                        <lifecycleMappingMetadata>
                            <pluginExecutions>
                                <pluginExecution>
                                    <pluginExecutionFilter>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-enforcer-plugin</artifactId>
                                        <versionRange>[1.0,)</versionRange>
                                        <goals>
                                            <goal>enforce</goal>
                                        </goals>
                                    </pluginExecutionFilter>
                                    <action>
                                        <ignore />
                                    </action>
                                </pluginExecution>
                            </pluginExecutions>
                        </lifecycleMappingMetadata>
                    </configuration>
                </plugin>
                
                
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.5.0</version>
                    <configuration>
                        <doclint>none</doclint>
                    </configuration>
                </plugin>
                
                <plugin>
                    <groupId>org.sonatype.plugins</groupId>
                    <artifactId>nexus-staging-maven-plugin</artifactId>
                    <version>1.6.8</version>
                    <extensions>true</extensions>
                    <configuration>
                        <serverId>ossrh</serverId>
                        <nexusUrl>https://oss.sonatype.org/</nexusUrl>
                        <autoReleaseAfterClose>true</autoReleaseAfterClose>
                    </configuration>
                </plugin>
                
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.12.1</version>
                    <dependencies>
                        <dependency>
                            <groupId>org.apache.maven.doxia</groupId>
                            <artifactId>doxia-module-markdown</artifactId>
                            <version>1.12.0</version>
                        </dependency>
                    </dependencies>
                </plugin>
            
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>2.8.2</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.2.1</version>
                </plugin>
            
                <plugin>
                    <groupId>org.eclipse.jetty</groupId>
                    <artifactId>jetty-maven-plugin</artifactId>
                    <version>${jetty.version}</version>
                </plugin>

                <plugin>
                    <artifactId>maven-archetype-plugin</artifactId>
                    <version>3.2.1</version>
                </plugin>
                
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>1.4.1</version>
                    <executions>
                        <execution>
                            <id>enforce-banned-dependencies</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <bannedDependencies>
                                        <excludes>
                                            <exclude>commons-logging</exclude>
                                        </excludes>
                                    </bannedDependencies>
                                </rules>
                                <fail>true</fail>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

    <reporting>
        <plugins>
            <plugin>